sudo: false
git:
  depth: 1
language: node_js
cache: yarn
node_js:
  - 4
  - 6
  - 7
after_script:
  - npm install istanbul-coveralls@1
  - npm run-script coverage
  - node node_modules/.bin/istanbul-coveralls
